[fruit and veg]
apples
aubergine
avocado
avocados
banana|bananas
beansprouts
beetroots
bell pepper|bell peppers
blueberries
bok choy
broccoli
cabbage
capsicum
carrot|carrots
cauliflower
celeriac
celery
cherry tomatoes
Chinese cabbage
cilantro
clementine
coconut
coriander
cos lettuce
courgette|courgettes
cucumber|cucumbers
dill
edamame
eggplant
fresh chili
fresh basil
fresh blueberries
fresh coriander
fresh oregano
fresh raspberries
fresh thyme
garlic
ginger
grapes
green beans
green peas
jalapeño pepper
kiwi|kiwis
lemon
lettuce
lime
mango
melon
mushrooms
nectarines
onion|onions
parsley
peaches
pears
peas
potatoes
raspberries
red bell pepper|red bell peppers|red peppers
red cabbage
red chilli
red onion|red onions
rocket|rocket salad
rosemary
salad leaves
scallions
shallot
shiitake mushrooms
snow peas
spinach|baby spinach
spring onions
sprouts
sweet potatoes
strawberries
thyme
tomatoes
zucchini

[milk and dairy]
butter
cheddar cheese
coconut milk
coconut yoghurt
cottage cheese
curd cheese
double cream
egg|eggs
feta
grated mozzarella
milk
mozzarella|mozzarella cheese
parmesan cheese
soft cheese
sour cream
whole milk

[meat and seafood]
bacon
beef cut
bream
catfish
chicken fillets
chicken thighs
cod
corn beef
duck
ground beef
lamb
lamb chops
parma ham
prawns
rashers
salmon slices
seabass
smoked salmon
turkey breast fillets
whole chicken

[breads and baked goods]
apple lattice pie
bake at home bread
breadcrumbs
breakfast biscuites
chiabatta|ciabatta
corn tortillas
croissant
doughnuts
profiteroles
rye sourdough
tea cake
tortilla|tortillas

[tinned goods and baking]
artichoke hearts
baked beans
black beans
cannellini beans
chickpea flour
chickpeas
chopped tomato
chopped tomatoes
corn starch
dry yeast
flour
fresh yeast
kalamata olives
passata
pickles
plain flour
redcurrant jelly
roasted peppers
roasted red peppers
strained kimchi
strong white flour
tin tomatoes
tinned peaches
tinned pineapples
tinned tomatoes
tipo zero flour
yeast

[packaged goods, pasta and sauces]
almonds
apple crisps
black rice
brown lentils
brown rice
black tea
capers
cashews
caster sugar
chia seeds
chicken broth
chicken stock
choclate bars
coffee
cooked rice
cous cous
crackers
crisps
dates
dried apricots
dried figs
dried plums
dried rice noodles
freekeh
frozen corn
frozen green beans
frozen peas
frozen tiger prawns
granola
jasmin rice
lentils
linguine pasta
mayonnaise
oat flakes
oats
peanut butter
pistachio
pumkin seeds
quinoa
raisins
sugar
sunflower seeds
sweet potato
tahini
tom yum
tomato paste
vegan mayonnaise
vegetable stock
vegetable stock cubes
walnuts
white quinoa
wholemeal pasta
wild rice

[dried herbs and spices]
bay leaves
black pepper
blue fenugreek
caraway
cayenne pepper
chilli
chilli flakes
chilli powder
Chinese five-spice powder
cinnamon
coriander seeds
cumin
cumin ground
curry seasoning powder
dried oregano
dried sage
fennel seeds
flaky salt
galangal
garam masala
garlic paste
garlic powder
ground black pepper
ground cinnamon
ground coriander
ground cumin
lemongrass
onion powder
oregano
mint
paprika
pepper
poultry seasoning
provence herbs
salt|sea salt
sesame seeds
smoked paprika
star anise
turmeric
white pepper

[oils and dressings]
apple cider vinegar
balsamic glaze
balsamic vinegar
blackstrap molasses
coconut oil
chilli oil
Chinese cooking wine
cider
Dijon mustard
extra virgin olive oil
flaxseed oil
lime juice
maple syrup
Marmite
Marsala
oil
olive oil
oyster sauce
peanut oil
rice wine vinegar
sesame oil
soy sauce
tamari
vinegar
white vinegar
white wine

[vegetarian]
firm tofu
nori sheet
nutritional yeast
tempeh
tofu
